BEGIN;

CREATE TABLE IF NOT EXISTS especialidades (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS pacientes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    data_nascimento DATE NOT NULL,
    sexo CHAR(1) NOT NULL,
    CONSTRAINT pacientes_sexo_check CHECK (sexo IN ('M', 'F'))
);

CREATE TABLE IF NOT EXISTS exames (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS consultas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id INTEGER NOT NULL,
    especialidade_id INTEGER NOT NULL,
    data_hora TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    compareceu BOOLEAN NOT NULL,
    CONSTRAINT consultas_paciente_fk
        FOREIGN KEY (paciente_id) REFERENCES pacientes (id),
    CONSTRAINT consultas_especialidade_fk
        FOREIGN KEY (especialidade_id) REFERENCES especialidades (id)
);

CREATE TABLE IF NOT EXISTS exames_solicitados (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id INTEGER NOT NULL,
    exame_id INTEGER NOT NULL,
    data_solicitacao DATE NOT NULL,
    CONSTRAINT exames_solicitados_paciente_fk
        FOREIGN KEY (paciente_id) REFERENCES pacientes (id),
    CONSTRAINT exames_solicitados_exame_fk
        FOREIGN KEY (exame_id) REFERENCES exames (id)
);

CREATE TABLE IF NOT EXISTS log_auditoria_faltas (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consulta_id INTEGER NOT NULL,
    paciente_id INTEGER NOT NULL,
    data_registro TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT log_auditoria_faltas_consulta_fk
        FOREIGN KEY (consulta_id) REFERENCES consultas (id),
    CONSTRAINT log_auditoria_faltas_paciente_fk
        FOREIGN KEY (paciente_id) REFERENCES pacientes (id)
);

CREATE INDEX IF NOT EXISTS consultas_paciente_id_idx ON consultas (paciente_id);
CREATE INDEX IF NOT EXISTS consultas_especialidade_id_idx ON consultas (especialidade_id);
CREATE INDEX IF NOT EXISTS exames_solicitados_paciente_id_idx ON exames_solicitados (paciente_id);
CREATE INDEX IF NOT EXISTS exames_solicitados_exame_id_idx ON exames_solicitados (exame_id);
CREATE INDEX IF NOT EXISTS log_auditoria_faltas_consulta_id_idx
    ON log_auditoria_faltas (consulta_id);
CREATE INDEX IF NOT EXISTS log_auditoria_faltas_paciente_id_idx
    ON log_auditoria_faltas (paciente_id);

CREATE OR REPLACE FUNCTION registrar_falta()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
    INSERT INTO log_auditoria_faltas (consulta_id, paciente_id)
    VALUES (NEW.id, NEW.paciente_id);

    RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_auditoria_falta ON consultas;

CREATE TRIGGER trg_auditoria_falta
AFTER UPDATE OF compareceu ON consultas
FOR EACH ROW
WHEN (OLD.compareceu IS DISTINCT FROM FALSE AND NEW.compareceu = FALSE)
EXECUTE FUNCTION registrar_falta();

DROP MATERIALIZED VIEW IF EXISTS mv_padroes_faltas;

CREATE MATERIALIZED VIEW mv_padroes_faltas AS
SELECT
    e.nome AS nome_especialidade,
    TO_CHAR(c.data_hora, 'Day') AS dia_semana,
    COUNT(c.id) AS total_agendamentos,
    COUNT(c.id) FILTER (WHERE c.compareceu = FALSE) AS total_faltas
FROM consultas c
JOIN especialidades e ON c.especialidade_id = e.id
GROUP BY e.nome, TO_CHAR(c.data_hora, 'Day');

DROP MATERIALIZED VIEW IF EXISTS mv_horarios_criticos_faltas;

CREATE MATERIALIZED VIEW mv_horarios_criticos_faltas AS
SELECT
    e.nome AS nome_especialidade,
    TO_CHAR(c.data_hora, 'Day') AS dia_semana,
    EXTRACT(HOUR FROM c.data_hora) AS hora,
    COUNT(c.id) AS total_faltas,
    RANK() OVER (
        PARTITION BY e.nome
        ORDER BY COUNT(c.id) DESC
    ) AS rank_criticidade
FROM consultas c
JOIN especialidades e ON c.especialidade_id = e.id
WHERE c.compareceu = FALSE
GROUP BY
    e.nome,
    TO_CHAR(c.data_hora, 'Day'),
    EXTRACT(HOUR FROM c.data_hora);

DROP MATERIALIZED VIEW IF EXISTS mv_ranking_exames_idade;

CREATE MATERIALIZED VIEW mv_ranking_exames_idade AS
WITH pre_processamento AS (
    SELECT
        ex.nome AS nome_exame,
        CASE
            WHEN EXTRACT(YEAR FROM AGE(CURRENT_DATE, p.data_nascimento)) < 18
                THEN 'Menor 18'
            WHEN EXTRACT(YEAR FROM AGE(CURRENT_DATE, p.data_nascimento)) BETWEEN 18 AND 59
                THEN '18-59'
            ELSE '60+'
        END AS faixa_etaria
    FROM exames_solicitados es
    JOIN pacientes p ON es.paciente_id = p.id
    JOIN exames ex ON es.exame_id = ex.id
),
contagem_exames AS (
    SELECT
        faixa_etaria,
        nome_exame,
        COUNT(*) AS total_solicitacoes
    FROM pre_processamento
    GROUP BY faixa_etaria, nome_exame
)
SELECT
    faixa_etaria,
    nome_exame,
    total_solicitacoes,
    RANK() OVER (
        PARTITION BY faixa_etaria
        ORDER BY total_solicitacoes DESC
    ) AS ranking
FROM contagem_exames;

COMMIT;
