BEGIN;

CREATE TABLE IF NOT EXISTS especialidades (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS pacientes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    data_nascimento DATE NOT NULL,
    sexo CHAR(1) NOT NULL,
    CONSTRAINT pacientes_sexo_check CHECK (sexo IN ('M', 'F'))
);

CREATE TABLE IF NOT EXISTS exames (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS consultas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id INTEGER NOT NULL,
    especialidade_id INTEGER NOT NULL,
    data_hora TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    compareceu BOOLEAN NOT NULL,
    CONSTRAINT consultas_paciente_fk
        FOREIGN KEY (paciente_id) REFERENCES pacientes (id),
    CONSTRAINT consultas_especialidade_fk
        FOREIGN KEY (especialidade_id) REFERENCES especialidades (id)
);

CREATE TABLE IF NOT EXISTS exames_solicitados (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id INTEGER NOT NULL,
    exame_id INTEGER NOT NULL,
    data_solicitacao DATE NOT NULL,
    CONSTRAINT exames_solicitados_paciente_fk
        FOREIGN KEY (paciente_id) REFERENCES pacientes (id),
    CONSTRAINT exames_solicitados_exame_fk
        FOREIGN KEY (exame_id) REFERENCES exames (id)
);

CREATE INDEX IF NOT EXISTS consultas_paciente_id_idx ON consultas (paciente_id);
CREATE INDEX IF NOT EXISTS consultas_especialidade_id_idx ON consultas (especialidade_id);
CREATE INDEX IF NOT EXISTS exames_solicitados_paciente_id_idx ON exames_solicitados (paciente_id);
CREATE INDEX IF NOT EXISTS exames_solicitados_exame_id_idx ON exames_solicitados (exame_id);

COMMIT;